
class Config {
  
  
  
  static const int totalLives = 5;
  static const int maxNumberBlocksInPlayArea = 2; // Legacy - keeping for compatibility
  static const int maxAutoGeneratedBlocks = 3; // Auto generation stops at 3 blocks
  static const int maxManualGeneratedBlocks = 5; // Manual generation stops at 5 blocks
  static const int scorePerCorrectBlock = 100;
  static const Duration blockGenerationInterval = Duration(milliseconds: 300);
  static const double blockGenerationChance = 0.9;
  static const double correctBlockProbability = 0.5; // Probability of generating a divisible block
  
  static const double bounceDamping = 0.8;
  static const double minHorizontalVelocity = -100.0; // Adjusted for mobile width (360px)
  static const double maxHorizontalVelocity = 100.0;
  
  // Animation
  static const Duration numberBlockAnimationDuration = Duration(milliseconds: 400);
  static const Duration blockCleanupDelay = numberBlockAnimationDuration;
  
  // Physics constants
  static const double targetFps = 60.0;
  static const double deltaTime = 1.0 / targetFps;
  
  // Audio constants
  static const double initialAudioLoadRatio = 0.5;
  
  // Game lifecycle
  static const Duration levelTransitionDelay = Duration(seconds: 2);
  
  // UI dimensions - Mobile optimized
  static const double playAreaWidth = 360.0; // Mobile-friendly width
  static const double playAreaHeight = 480.0; // Mobile-friendly height
  static const double numberBlockWidth = 60.0;
  static const double numberBlockHeight = 40.0;
  
  
}